In [15]:
import json
import pandas as pd

In [16]:
with open('jobs.json', 'r') as infile:
    json_data = json.load(infile)

In [17]:
df = pd.json_normalize(json_data)

In [18]:
df['Job Title'] = df['Job Title'].str.replace('CDI', '', case=False).str.strip()
df['Job Title'] = df['Job Title'].str.replace('cdi', '', case=False).str.strip()
df

,Job Title,Job Location,Company Name,Job Type
0,Software Engineer (Python / React),Paris,Manty,CDI
1,Développeur backend senior - Nantes (Java/Pyt...,Nantes,Artelys,CDI
2,Developer Fullstack Python/react- Lyon,Paris,The Product Crew,CDI
3,Développeur/se Backend Python,Paris,The Product Crew,CDI
4,Développeur/se Fullstack Python/React,Paris,The Product Crew,CDI
5,Ingénieur de développement Python sur la virtu...,Lannion,Orange,CDI
6,Stage - PoC ordonnanceur AirFlow/Python dans l...,Marseille - 3ème Arrondissement,Orange,Stage
7,Senior Python Backend Engineer,Paris,Yavin,CDI
8,Développeur Python (H/F),Paris,Groupe SII,CDI
9,"Ingénieur Intégration Logiciel QA (Python, Lin...",Paris,Aldebaran - United Robotics Group,CDI
10,STAGE - Ingénieur - Développement Logiciel de ...,Moirans,Thales,Stage
11,Ingénieur(e) Développeur / Intégrateur (C++/Py...,Nantes,Thales,CDI
12,Tech Lead Python dans le domaine des GNSS (H/F),Toulouse,Thales,CDI
13,une Ingénieur(e) Validation (Python) (H/F),Nantes,Thales,CDI
14,Ingénieur Développement Python,Bordeaux,Thales,CDI
15,Développeur(euse) Python confirmé(e) / Consult...,Paris,Innovela,CDI
16,Développeur(euse) Fullstack Python / Angular,Paris,Innovela,CDI
17,Ingénieur Développement Python et C - PARIS (H/F),Paris,Capgemini,CDI
18,"Fullstack Software Engineer (Python, ReactJS)",Paris,GitGuardian,CDI
19,Staff Software Engineer (Python),Paris,GitGuardian,CDI
20,Backend Software Engineer (Python),Paris,GitGuardian,CDI
21,Trading Systems - Développeur Python - H/F,Paris,MARGO,CDI
22,Stage - Développeur Python pour Web Scraping A...,33281 Merignac,Enedis,Stage
23,Ingénieur Back-end Python,Bordeaux,Adservio,Autres
24,Développeur Python H/F,Paris,EXTIA,CDI
25,Développeur Python H/F,Montpellier,EXTIA,CDI
26,Développeur Python (H/F),Paris,EXTIA,CDI
27,Stage - Développeur Python (H/F),Toulouse,Capgemini,Stage
28,Lead Développeur Python - Rennes - (f/m/x),Rennes,IDnow France,CDI
29,Développeur.se Python Expérimenté.e (f/d/m)- R...,Rennes,IDnow France,CDI
30,Développeur Python,Vincennes,Accenta,CDI
31,Développeur-Développeuse junior(e) Python/Django,Toulouse,Makina Corpus,CDI